### ISSUE TITLE
Option to pass textarea name

### ISSUE THREAD

**Issue by Maarten88** [mlowen/CommonMark.Editor#2]
I found this project which was exactly what I needed. A simple commonmark editor in Bootstrap, nice!
I was testing it with an oldfashioned form post, but what I missed was a way to specify a name for the textarea so that the text can bind to the correct field. I worked around it by setting the name using jquery during initialization, but it would be nicer if there was a 'name' option just like i.e. 'text'.

**Comment by mlowen** [comment]
I'm glad you like it, I agree that adding a `name` option would be the nicest way to do it. Will look at adding it in the next day or so.

**Comment by mlowen** [comment]
Hi @Maarten88 this piece of functionality was included in the [0.3.0 release](https://github.com/mlowen/CommonMark.Editor/releases/tag/0.3.0), thanks for passing along the idea.

**Comment by Maarten88** [comment]
I have removed my workaround and it works great, thx!
