### ISSUE TITLE
Cursor behaviour in IE

### ISSUE THREAD

**Issue by Maarten88** [mlowen/CommonMark.Editor#3]
After typing any special character (like #, * or [) in IE (I'm using version 11) the cursor jumps to the end of the document. In Chrome or FF this does not happen, the cursor stays where it is.

**Comment by mlowen** [comment]
Hi @Maarten88 this issue has been fixed and is part of the [0.3.0 release](https://github.com/mlowen/CommonMark.Editor/releases/tag/0.3.0).

**Comment by Maarten88** [comment]
You even fixed this bug for IE, tnx!
