### ISSUE TITLE
Commonmark now using Parser instead of DocParser

### ISSUE THREAD

**Issue by cfergus** [mlowen/CommonMark.Editor#4]
It appears that commonmark.js is now using commonmark.Parser instead of commonmark.DocParser, as of release 0.17 or so.

For CommonMark.Editor, the documentation recommends including the latest lib from source.
Suggest both:

* Updating the docs to reference the last known version of commonmark that is supported
* Updating the lib to use the new "Parser" variant.

**Comment by mlowen** [comment]
This issue has been fixed in [v0.3.1](https://github.com/mlowen/CommonMark.Editor/releases/tag/0.3.1) and the [README](https://github.com/mlowen/CommonMark.Editor/blob/master/README.md) has been updated to better reflect the version of the dependencies that CommonMark.Editor is tested against.
